name: CMake

on:
  push:
    branches: [main]
    
  pull_request:
    branches: [main]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ./vcpkg
          key: v1

      - name: Install Packages
        run: bash scripts/download-dep.sh

      - name: Configure CMake
        run: cmake -B build -DCMAKE_TOOLCHAIN_FILE=./vcpkg/scripts/buildsystems/vcpkg.cmake

      - name: Build
        run: cmake --build build

      - name: Test
        working-directory: build
        run: ctest --output-on-failure
